name: new-work

services:
  work-svc:
    image: airsss/work-svc:latest
    container_name: work-svc
    ports:
      - "8070:8070"
    env_file:
      - .env
    environment:
      - WEB_URL=${WEB_URL}
      - LDAP_URL=${LDAP_URL}
      - GITBUCKET_URL=${GITBUCKET_URL}
      - GITBUCKET_API_KEY=${GITBUCKET_API_KEY}
    volumes:
      - /storage/Photos:/app/photos
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8070/api/ping" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - work-network

  work-web:
    build:
      context: ./work-rework
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
    image: airsss/work-web:latest
    container_name: work-web
    restart: unless-stopped
    ports:
      - "5172:5172"
    networks:
      - work-network

networks:
  work-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16